#!/usr/bin/env python
import sys

# TODO: Enable parsing without flags 
# TODO: Use ArgParse instead of OptParse
# Move into /usr/local/bin/gitshit
def main():
    parser = OptionParser(usage="usage: %prog [options] filename",
                          version="%prog 1.0")
    parser.add_option("-f", "--filename",
                      action="store_true",
                      dest="xhtml_flag",
                      default=False,
                      help="create a XHTML template instead of HTML")
    parser.add_option("-m", "--message",
                      action="store", # optional because action defaults to "store"
                      dest="cssfile",
                      default="style.css",
                      help="CSS file to link",)
    (options, args) = parser.parse_args()

    if len(args) != 1:
        parser.error("wrong number of arguments")

    print options
    print args

if __name__ == '__main__':
    main()
    # print("Hello, this feature in gitshit hasn't been fleshed out yet")

